site_name: Passio

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/fenixpapu
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/phoenixpapu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/phoenixpapu/

copyright: |
  &copy; 2023 <a href="https://github.com/fenixpapu"  target="_blank" rel="noopener">PaPu</a>
